name: kraken
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - python-bidi
  - lxml
  - regex
  - requests
  - click>=8.1
  - numpy~=1.23.0
  - pillow~=9.2.0
  - scipy~=1.10.0
  - jinja2~=3.0
  - conda-forge::torchvision-cpu>=0.5.0
  - conda-forge::pytorch-cpu>=1.11,<1.14
  - jsonschema
  - scikit-learn~=1.2.1
  - scikit-image~=0.22.0
  - shapely~=1.8.5
  - pyvips
  - imagemagick>=7.1.0
  - pyarrow
  - importlib-resources>=1.3.0
  - conda-forge::pytorch-lightning~=2.0.0
  - conda-forge::torchmetrics>=1.1.0
  - conda-forge::threadpoolctl~=3.2
  - pip
  - albumentations
  - rich
  - pip:
    - coremltools~=6.0
    - file:.
