name: kraken
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - python-bidi
  - lxml
  - regex
  - requests
  - click>=8.1
  - numpy
  - pillow>=6.2.2
  - scipy
  - jinja2
  - conda-forge::torchvision-cpu>=0.5.0
  - conda-forge::pytorch-cpu>=1.7.1,<=1.13
  - jsonschema
  - scikit-image>=0.17.0,<=0.19.3
  - shapely>=1.8
  - pyvips
  - imagemagick>=7.1.0
  - coremltools>=3.3
  - pyarrow
  - conda-forge::pytorch-lightning
  - pip
  - albumentations
  - rich
  - pip:
    - file:.
