name: kraken
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - python-bidi
  - lxml
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow>=6.2.2
  - scipy
  - protobuf>=3.0
  - jinja2
  - conda-forge::torchvision
  - conda-forge::pytorch>=1.5.0,<1.11
  - cudatoolkit>=9.2
  - jsonschema
  - scikit-image>=0.17.0
  - shapely
  - pyvips
  - imagemagick>=7.1.0
  - coremltools>=3.3
  - pyarrow
  - pip
  - pip:
    - file:.
