name: kraken
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - python-bidi
  - lxml
  - regex
  - requests
  - click>=8.1
  - numpy~=1.23.0
  - pillow~=9.2.0
  - scipy
  - jinja2~=3.0
  - conda-forge::torchvision-cpu>=0.5.0
  - conda-forge::pytorch-cpu>=1.7.1,<1.14
  - jsonschema
  - scikit-learn~=1.2.1
  - scikit-image>=0.17.0,<=0.19.3
  - shapely==1.8.5
  - pyvips
  - imagemagick>=7.1.0
  - pyarrow
  - conda-forge::pytorch-lightning~=2.0.0
  - conda-forge::torchmetrics>=0.10.0
  - pip
  - albumentations
  - rich
  - pip:
    - coremltools~=6.0
    - file:.
