name: kraken
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - python-bidi
  - lxml
  - future
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow>=6.2.2
  - scipy
  - protobuf>=3.0
  - jinja2
  - pytorch::torchvision>=0.5.0
  - cpuonly
  - pytorch::pytorch>=1.5.0,<=1.7.0
  - jsonschema
  - scikit-image<=0.17.2
  - shapely
  - pip
  - pyvips
  - imagemagick<7.0.9
  - pip:
    - coremltools>=3.3
    - git+https://github.com/mittagessen/kraken.git@master
