name: kraken
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - python-bidi
  - lxml
  - regex
  - requests
  - click>=8.1
  - numpy<=1.23.99
  - pillow>=9.2.0
  - scipy
  - jinja2
  - conda-forge::torchvision
  - conda-forge::pytorch>=1.7.1,<1.14
  - cudatoolkit>=9.2
  - jsonschema
  - scikit-image>=0.17.0,<=0.19.3
  - shapely==1.8.5
  - pyvips
  - imagemagick>=7.1.0
  - coremltools>=6.0
  - pyarrow
  - conda-forge::pytorch-lightning>=1.7.0
  - conda-forge::torchmetrics>=0.10.0
  - pip
  - albumentations
  - rich
  - pip:
    - file:.
